import os
import oracledb
from dotenv import load_dotenv

# Carrega as variáveis de ambiente
load_dotenv()

try:
    print("Conectando ao Oracle Cloud...")
    conexao = oracledb.connect(
        user=os.getenv("DB_USER"),
        password=os.getenv("DB_PASS"),
        dsn=os.getenv("DB_DSN")
    )
    cursor = conexao.cursor()

    # 1. Cria a Tabela Domínio
    print("Criando a tabela TB_MOEDA...")
    cursor.execute("""
        CREATE TABLE TB_MOEDA (
            ID_MOEDA NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            NOME_MOEDA VARCHAR2(50) NOT NULL UNIQUE,
            SIMBOLO VARCHAR2(5) NOT NULL
        )
    """)

    # 2. Insere as Moedas Iniciais
    print("Inserindo Dólar e Euro no sistema...")
    cursor.execute("INSERT INTO TB_MOEDA (NOME_MOEDA, SIMBOLO) VALUES ('Dólar', 'USD')")
    cursor.execute("INSERT INTO TB_MOEDA (NOME_MOEDA, SIMBOLO) VALUES ('Euro', 'EUR')")
    conexao.commit()

    # 3. Cria a Tabela Fato com as Chaves Estrangeiras
    print("Criando a tabela normalizada TB_COTACAO...")
    cursor.execute("""
        CREATE TABLE TB_COTACAO (
            DATA_COTACAO DATE NOT NULL,
            ID_MOEDA NUMBER NOT NULL,
            PRECO_COMPRA NUMBER(10, 4) NOT NULL,
            PRECO_VENDA NUMBER(10, 4) NOT NULL,
            VOLUME NUMBER(15, 2),
            
            CONSTRAINT PK_COTACAO PRIMARY KEY (DATA_COTACAO, ID_MOEDA),
            CONSTRAINT FK_COTACAO_MOEDA FOREIGN KEY (ID_MOEDA) REFERENCES TB_MOEDA(ID_MOEDA)
        )
    """)

    print("🚀 SUCESSO! A nova fundação do banco de dados está pronta!")

except Exception as erro:
    print("Falha na operação. Erro:", erro)
finally:
    if 'cursor' in locals():
        cursor.close()
    if 'conexao' in locals():
        conexao.close()
        print("Conexão encerrada.")